apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: test-retain-replicas
  namespace: retain-test
  labels:
    opa-gatekeeper.zendesk.com/pre-stop-required: "false"
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: sample-deployment
  behavior:
    scaleDown:
      selectPolicy: Disabled
    scaleUp:
      selectPolicy: Disabled
  minReplicas: 2
  maxReplicas: 2
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 10
